version: '3'

services:
  detectionplate:
    image: "logpyx/aperam:1.0"
    environment:
      IP_MQTT: gwqa.revolog.com.br
      PORT_MQTT: 1884
      USER_NAME_MQTT: tecnologia
      PASSWORD_MQTT: 128Parsecs!
      PUBLISH_TOPIC: aperam/plate
      TESSERACT_GRAY: 130
      SCALE_FACTOR_CASCADE: 1.7
      CAMERA_SOURCE: rtsp://admin:128Parsecs!@192.168.15.85/Streaming/channels/101
      TIME_OUT_SEND_PLATE: 5
      MIN_LINE_FRAME: 100
      MAX_LINE_FRAME: 900