version: '3'

services:
  detectionplate:
    image: "logpyx/aperam:1.0"
    environment:
      IP_MQTT: 10.50.239.100
      PORT_MQTT: 1884
      USER_NAME_MQTT: tecnologia
      PASSWORD_MQTT: 128Parsecs!
      PUBLISH_TOPIC: aperam/plate
      PUBLISH_TOPIC_STATUS: aperam/status
      TESSERACT_GRAY: 130
      SCALE_FACTOR_CASCADE: 1.7
      CAMERA_SOURCE: rtsp://admin:128Parsecs!@10.50.239.20/Streaming/channels/101
      TIME_OUT_SEND_PLATE: 5
      MIN_LINE_FRAME: 200
      MAX_LINE_FRAME: 900
      MAX_PLATES: 100